### ISSUE TITLE
redux-thunk present unnecessarily in package*json

### ISSUE THREAD

**Issue by marcindulak** [fullstack-hy2020/redux-notes#14]
The braches part6-3 to part6-5 use `import { configureStore } from '@reduxjs/toolkit'` so explicit redux-thunk should not be needed

https://github.com/fullstack-hy2020/redux-notes/blob/d5758d802d4d6460fefe77c2e1f4e739d58b0148/package.json#L16

**Comment by mluukkai** [comment]
removed
